package pl.edu.pwr.pp;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.charset.StandardCharsets;

import static java.nio.file.StandardOpenOption.*;

public class ImageFileWriter {

	public void saveToTxtFile(char[][] ascii, String fileName) {
		// np. korzystając z java.io.PrintWriter
		// TODO Wasz kod
		
		Path path = Paths.get(Paths.get("").toAbsolutePath().toString() + "/results/" + fileName);
		
		if(!Files.exists(path))
		{
			try {
				Files.createFile(path);
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
		
		try (BufferedWriter writer = Files.newBufferedWriter(path, StandardCharsets.UTF_8, WRITE, CREATE, TRUNCATE_EXISTING)){
			
			int columns = ascii.length;
			int rows = ascii[0].length;
			
			writer.write("P2\n");
			writer.write("#ASCII-ART generated by magnificent program\n");
			writer.write(rows + " " + columns + "\n");
			writer.write("255\n");
			
			for(int x = 0; x < columns; x++)
			{
				for(int y = 0; y < rows; y++)
					writer.write(ascii[x][y] + "\t");
				
				writer.write("\n");
			}
			
			writer.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
